### ISSUE TITLE
How to save results as a new variable from the self created function

### ISSUE THREAD

**Issue by ilya1010** [datascience-mobi/2021-topic-01-team-03#3]
These are the lines with repetitive parts (196-208) from play around
``` R
effective_drugs<-function(x){
  effective_x<-x[,which(apply(x,2,mean)<=0.2)]
  return(effective_x)
}

effective_d1=effective_drugs(d1)
effective_d2=effective_drugs(d2)
effective_d3=effective_drugs(d3)
effective_d4=effective_drugs(d4)
effective_d5=effective_drugs(d5)
effective_d6=effective_drugs(d6)
effective_d7=effective_drugs(d7)
effective_d8=effective_drugs(d8)
```

How would you avoid repeating the unnecessary code? I tried to create a function to save the results into new variable but it did not work. Could you please give me some suggestions to solve it?

**Comment by sholderbach** [comment]
To make this effective you need to start avoiding the code duplication at the point where you define the doses. 
Rough idea:
- list binding shorthand names to concentrations 
- use that list to map a function that filters the colum names 
- with this new list to create a list of subsetted data.frames
...

For the snippet:

Assume you already have a list `test_stuff` of whatever the d1...d8 are:
``` R
test_stuff <- list(d1 = d1, d1 = d2, d3 = d3, d4 = d4, d5 = d5, d6 = d6, d7 = d7, d8 = d8)
```

So with that style of input the code would simplify to:

``` R
select_effective_drugs<-function(x){
  effective_x<-x[,which(apply(x,2,mean)<=0.2)]
  return(effective_x)
}
effective_test_stuff <- lapply(test_stuff, select_effective_drugs)
```

(I would recommend naming the function with a verb to express what it is doing)

**Comment by ilya1010** [comment]
That is a great idea to work with lists, thanks for the suggestion! I have just tried it out on the example we have discussed to see how it works and there is something weird happening:

`doses_subsets <- list(d1 = d1, d2 = d2, d3 = d3, d4 = d4, d5 = d5, d6 = d6, d7 = d7, d8 = d8)
effective_test_stuff <- lapply(doses_subsets, effective_drugs)
View(effective_test_stuff[[1]])

effective_d1=effective_drugs(d1)`

When I compare the result of the first list element with the list it gives me a data frame with 241 variables. However, if I compute the effective_drugs function the way we had it before it gives me a data frame with 294 variables. So for some reason when applying the effective_drugs  on a list we lose drugs. This happens in all 8 dataframes. do you know what this could be attributed to?

**Comment by ilya1010** [comment]
I have double-checked it now and it works. I have done the same procedure as last time, started off with an empty repository, kommisch aber hauptsache es funktioniert. I am gonna try and implement this list strategy in other parts of our code. Thanks a lot, Stefan!

**Comment by ilya1010** [comment]
I would now have a follow-up question about following chunk:

```
new_colnames<-function(x){
  a<-gsub(pattern = "::.*", replacement = "", colnames(x))
  return(a)
}
colnames(effective_d1)<-new_colnames(effective_d1)
colnames(effective_d2)<-new_colnames(effective_d2)
colnames(effective_d3)<-new_colnames(effective_d3)
colnames(effective_d4)<-new_colnames(effective_d4)
colnames(effective_d5)<-new_colnames(effective_d5)
colnames(effective_d6)<-new_colnames(effective_d6)
colnames(effective_d7)<-new_colnames(effective_d7)
colnames(effective_d8)<-new_colnames(effective_d8)
## remove everything but the drug information from colnames and make them new colnames of the dataframes

save_new_colnames=function(y){
  colnames(y)<-new_colnames(y)
}
save_new_colnames(effective_d4)
```

Here at the beginning, I create a function to generate new colnames. In the end, I tried to create a second function that would substitute the old colnames for the new ones. However, this part would not be saved in the repository, so I made it manually in the middle. Now having my effective drugs in form of a list saves me some lines of code, but it does not solve the problem that the new colnames are not assigned. Any tips for that?

**Comment by sholderbach** [comment]
`colnames(df)<-` binds the strings in a vector on the rhs to the colnames attribute of the provided `df` object. But I think in this case the passing convention of R might be an issue. i.e. `y` is passed in. Gets locally modified in the scope of  the function but due to copy on write semantics, this does not affect the object originally outside the function that was passed in. (My first hunch... Did not investigate that yet, and I'm not the R pro to know the exact rules from the top of my head)

**Comment by sholderbach** [comment]
May be try returning y and thus have a functional programming style function and not a mutating procedure.

**Comment by ilya1010** [comment]
Hmm okay I will have a look at how we can optimize that part
