### ISSUE TITLE
Performance Shapiro test

### ISSUE THREAD

**Issue by XeniaTamara** [datascience-mobi/2021-topic-01-team-03#4]
Hey Stefan,
I was trying to perform a Shapiro test but the error "Fehler in FUN(newX[, i], ...) : all 'x' values are identical" occured. I thought I have to remove columns with identical values in all rows, so I did this:

 ```
# Removal of columns with identical entries

for (i in ncol(brain_cancer_exp)){
    if(min(brain_cancer_exp[,i]) == max(brain_cancer_exp[,i]))
    bc_exp_removed = brain_cancer_exp[,-i]
}


# checking data for normality by applying a shapiro test on each column 

bc_exp_shap = apply(bc_exp_removed,2,shapiro.test)
bc_exp_shap_res = sapply(bc_exp_shap,`[`,  c("p.value")) # genes which do have a normal distributed expression
bc_exp_norm = which(bc_cnv_shap_res > 0.95)
```

But the error is still existent. Do you have any recommendation how to treat it?

**Comment by sholderbach** [comment]
With that for loop you always assign a new value to the name bc_exp_removed so I don't think that it contains what you expect.

There is the `Filter()` function (capital F) that can create a new collection based on the boolean return of a function predicate.

Alternatively you can transpose it as rows in a data frame and use the `dplyr::filter` function as well which has some niceties for filtering data frames

Also if you are unsure if you set the parameters of the test correctly wrap the call in an anonymous function and provide the correct settings there.

**Comment by XeniaTamara** [comment]
Thanks for answering, I am going to try out these ways!

**Comment by XeniaTamara** [comment]
Hello Stefan, 
I am still stuck with this task... I completed a tidyverse course in DataCamp to get familiar with using the dpylr::filter. But the way it was presented there is not useful for the .exp data frame because it filters for categorical data. Do you have another suggestion how this function can be used without defining criteria?

Example how it was explained in the course:
````
filter(gapminder, country== "Albania")
````

**Comment by sholderbach** [comment]
If you want to summarize the column information first, there are special functions for that:

https://dplyr.tidyverse.org/reference/c_across.html

Filter should work on expressions based on named columns.

https://dplyr.tidyverse.org/reference/filter.html
