### ISSUE TITLE
Wilcoxon Test

### ISSUE THREAD

**Issue by XeniaTamara** [datascience-mobi/2021-topic-01-team-03#5]
Hello Stefan, 

we`ve got another issue for you :D 
We managed performing the Shapiro test and removed all genes that are normally expressed in our brain cancer cell lines. 
Now we want to perform Wilcoxon test, so we created, as you suggested in Tut on Wednesday, a reference cell line by computing the mean on all non brain cancer cell lines. 
We did a Signed Rank Test, which compared each of our cell lines with the reference one. This way we can tell how different our cell lines from the reference are.... However, it doesn't give us an information regarding each specific gene. 
But how could we perform the Wilcoxon test genewise and not celllinewise?

**Comment by sholderbach** [comment]
What do you mean by normally expressed and how did you apply the Shapiro Wilk test for that? It will tell you if the underlying population of am i.i.d. sample is normally distributed

Yes the Wilcoxon signed rank test only identifies the presence of a global difference between the paired samples with non random direction and was thus a not really helpful suggestion on its own. I am currently not really sure what the best way to do that is without introducing additional theory or making strong assumptions. Will try to get back to @carlherrmann on that.

**Comment by sholderbach** [comment]
If you have two larger samples with roughly equal size you could run a Mann-Whitney-U/Wilcoxon test for each gene and assume: 
- that the H0 is that the expression value for the gene comes from the same distribution 
- the groups are meaningful
- Alternative that the group gene exp values come from two distributions with different central measures
The power of this test is likely abysmal as no assumptions about the distribution of values and errors are made directly and it depends on more samples per group for both higher power and considered variation.

**Comment by XeniaTamara** [comment]
Thanks for answering that fast!
Concerning your first question: as you mentioned in an email, we performed the shapiro test first on our .exp dataframe of brain cancer cell lines to remove the genes that are normally distributed that afterwards, we can perform Wilcoxon on the non-normally distributed genes.  We did it like this:
```
# Filtering genes that have no variance
bc_exp_var <- apply(brain_cancer_exp,2,var)
bc_exp_no_var <- which(bc_exp_var==0)
bc_exp_high_var <- brain_cancer_exp[,-bc_exp_no_var]
bc_exp_high_var <- apply(bc_exp_high_var,2,as.numeric)

#Listing all gene variances
exp_list <- vector(mode = "list", length = ncol(s))
for(i in 1:ncol(bc_exp_high_var)) {         
  exp_list[[i]] <- bc_exp_high_var[ , i]
}

# checking data for normality by applying a shapiro test on list element
bc_exp_shap = lapply(exp_list,shapiro.test)

# Keeping p values in another list
exp_pvalue <- vector(length = ncol(bc_exp_high_var))
for(i in 1:ncol(bc_exp_high_var)) {         
  exp_pvalue[i] <- bc_exp_shap[[i]]$p.value
} 

# Selecting genes with a p value smaller than 0.5%
bc_exp_norm = which(exp_pvalue > 0.95)
bc_exp_not_norm=brain_cancer_exp[,-bc_exp_norm]
```

**Comment by XeniaTamara** [comment]
Concerning your idea of using the Mann-Whitney-U/Wilcoxon test instead: we have to get informed how the test works exactly but we are a bit frustrated as it took us days to figure out how we want to apply the Wilcoxon test.
But yesterday, we had an alternative idea, maybe this one is valid too: 
We performed an unpaired Wilcoxon test between the .exp dataframe with the brain cancer cell lines against a new .exp dataframe with all non brain cancer cell lines. 
```
wilcox.test(as.numeric(non_bc_exp[,1]),as.numeric(bc_exp_not_norm[,1]),paired = F)

wilcox_genes <- vector(mode = "list",length = 18699)
for(i in 1:18699) {         
  wilcox_genes[[i]] <- wilcox.test(as.numeric(non_bc_exp[,i]),as.numeric(bc_exp_not_norm[,i]),paired = F)
}

wilcox_pvalue_genes <- vector(length = 18699)
for(i in 1:18699) {         
  wilcox_pvalue_genes[i] <- wilcox_genes[[i]]$p.value
}
```
The disadvantage is that an alpha of 0.05 leads to around 9500 genes that are significantly different expressed in brain cancer compared to non brain cancer. This is alot...

**Comment by sholderbach** [comment]
I think this came from the quote from Carl and referred to the recommended use of the Shapiro-Wilk test to verify that samples are normally distributed to use in the following step a test assuming normality (if you can confirm that you can use t-tests or ANOVA as well instead of Mann-Whitney U/ Wilcoxon rank sum to get more power)
> Concerning your first question: as you mentioned in an email, we performed the shapiro test first on our .exp dataframe of brain cancer cell lines to remove the genes that are normally distributed that afterwards, we can perform Wilcoxon on the non-normally distributed genes.

**Comment by sholderbach** [comment]
> The disadvantage is that an alpha of 0.05 leads to around 9500 genes that are significantly different expressed in brain cancer compared to non brain cancer. This is alot...

How did you control for multiple testing? Bonferroni? Benjamini-Hochberg?

**Comment by XeniaTamara** [comment]
> 
> 
> I think this came from the quote from Carl and referred to the recommended use of the Shapiro-Wilk test to verify that samples are normally distributed to use in the following step a test assuming normality (if you can confirm that you can use t-tests or ANOVA as well instead of Mann-Whitney U/ Wilcoxon rank sum to get more power)

We were able to verify a normal distribution for only 300 of 18000 genes, so we removed these ones as we wanted to test the differential expression for only those that are not normally distrubuted. I hope that this was ment with it.

**Comment by XeniaTamara** [comment]
> 
> 
> How did you control for multiple testing? Bonferroni? Benjamini-Hochberg?

Well, I think we`ve missed something. We are going to figure that out tomorrow!

**Comment by sholderbach** [comment]
> We were able to verify a normal distribution for only 300 of 18000 genes, so we removed these ones as we wanted to test the differential expression for only those that are not normally distrubuted. I hope that this was ment with it.

Normality is only necessary precondition for t-tests to be considered, this is not related to Wilcoxon non-parametric tests (there are some assumptions as well but neglibible if similarly sized samples exist and i.i.d can be assumed)

**Comment by XeniaTamara** [comment]
> 
> How did you control for multiple testing? Bonferroni? Benjamini-Hochberg?

Thanks for saying, we totally forget that we have to do a correction when performing multiple testing. 
Now we performed both, Bonferroni and BH and with a significance level of 1% we receive with Bonferroni 1915 genes and with BH 6559 genes. Although I read in an article that BH is a better method when examining gene expression, Bonferroni leads to a better output. 
I don't know if it makes sense to further discuss this in this issue since we don't know whether you like our testing in general. Maybe it's better to discuss it on Wednesday in person.

**Comment by sholderbach** [comment]
BH attempts to maintain more power compared to bonferroni so that's expected. Maybe also compute the log-fold-change between the mean/median expression to assess the effect size. The proposed number of differentially expressed genes seems definitely greater than chance (not unreasonable given the assumption change in expression between brain cells/tumours and other cancer stuff). But with that alpha cutoff it seems somewhat impractical. I didn't assess your implementation so no direct sanity check on my side on that.

**Comment by XeniaTamara** [comment]
Now we computed the log-fold-change via the `foldchange` function from the gtools package between the means of all genes from the brain cancer and non brain cancer dataframes. 
But we don´t know how we could get to the effect size from these values. 
For comparison, we used the `cohen.d` function from the effsize package which calculates the effect size directly. These values are completely different. 
We really don't know what we've done :D 
Hope you could give us advices tomorrow!
