### ISSUE TITLE
Volcano plot

### ISSUE THREAD

**Issue by ilya1010** [datascience-mobi/2021-topic-01-team-03#7]
Hallo Stefan,

wir haben eine neue Issue für dich, hier ist unsere code:

```
#install.packages("gtools")
library(gtools)
bc_exp_mean=apply(brain_cancer_exp[,b_correction],2, mean)
non_bc_exp_mean=apply(non_bc_exp[,b_correction],2,mean)

logfc<-log2(bc_exp_mean/non_bc_exp_mean)
logpv=-log10(b_correction)
df <- data.frame(log2fc,log10pv)
library(ggplot2)
ggplot(df, aes(x=logfc, y=logpv)) +
  geom_point()
```

Wir haben versucht ein Volcano plot zu machen. Wir haben für jedes gen in 2 verschiedenen Datensätze Mittelwert genommen und damit ein log2foldchange gerechnet. Danach haben wir -log10 von unseren nach Bonferroni corregierten p-values gemacht und dann geplottet. Wir beobachten aber etwas sehr komisches, auf jeden Fall kein volcano plot. 

Woran könnte es liegen?

Dankee

**Comment by sholderbach** [comment]
Könnt ihr einen Screenshot mit rein packen? Log von einem ratio könnt ihr ja auch einfach mit einer eigenen Funktion berechnen, wenn ihr dem package nicht vertrauen wollt. Beachten müsst ihr nur für welche Werte das nicht definiert ist!

**Comment by ilya1010** [comment]
# #
![Screenshot (134)](https://user-images.githubusercontent.com/82601575/123514243-37858a80-d692-11eb-9d92-1c754e8621f1.png)

**Comment by XeniaTamara** [comment]
Wir haben den log von der ratio mit einer eigenen Funktion berechnet, das Package oben in Code ist noch ein Überrest von einem anderen Versuch, den wir dann verworfen haben.

**Comment by sholderbach** [comment]
Das sieht so als ob ihr einen one-sided test verwendet habt. Fuer diese large scale screens two-sided ist vermutlich sinnvoller. Desweiteren, habt ihr die Gruppen jeweils z-scaled?

**Comment by XeniaTamara** [comment]
> 
![Volcano plot](https://user-images.githubusercontent.com/82606553/123516910-d44e2500-d69e-11eb-9075-569475935c62.jpg)

**Comment by XeniaTamara** [comment]
Wir haben nun die Funktion ```scale()```` verwendet und so eine Z-Transformation für die Datensets ausgeführt. Unser Wilcoxon-Test ist bereits zweiseitig gewesen.
Nun haben wir aber auch Werte bei 0, was nicht sein kann. Zudem ist eine komische Fehlermeldung aufgetaucht (siehe Bild). Hast du weitere Ideen, woran es liegen könnte?

**Comment by sholderbach** [comment]
Seid ihr mit den skalierten Daten auch in den Test gegangen?

**Comment by sholderbach** [comment]
Ist die y-Achsenbeschriftung richtig?

**Comment by XeniaTamara** [comment]
> 
> 
> Seid ihr mit den skalierten Daten auch in den Test gegangen?

Haha, good point! Das haben wir tatsächlich vergessen.
Nun ist aber das Problem aufgetreten, dass bei der Anwendung der Z-Transformation einige Spalten wegfallen, warum ist für uns unerklärlich. Danach funktioniert unser Wilcoxon-Test nicht mehr, weswegen wir es darauf zurück führen, dass eine unterschiedliche Anzahl an NAs auftreten und so unsere Datensets unterschiedlich viele Spalten haben.
Es kommt die Fehlermeldung: "Not enough 'y' observations."

**Comment by XeniaTamara** [comment]
Hallo Stefan, were we go again.
Wir haben nun einen pseudo value in ```brain_cancer_exp``` global ermittelt und den gleichen Wert zudem auf unsere non-brain cancer cell lines aufaddiert (fanden wir logischer als zwei verschiedene zu verwenden). 
Nun haben wir danach die Z-Transformation durchgeführt und den Wilcoxon test gemacht uuuuuund er funktioniert immernoch nicht. 
Es muss also an irgendwas anderes liegen. Hast du noch eine Idee, was wir machen können?

**Comment by sholderbach** [comment]
Wie ist es ohne Z-Trafo

Funktioniert nicht ist mir zu ungenau. Faellt euch etwas bei den input werten auf. werden die selben dimensionen verwendet. Wo tritt die bestimmte fehlermeldung auf.

**Comment by XeniaTamara** [comment]
Ohne die Z-Transformation funktioniert der Loop. Die Dimension der Dataframes sind nicht gleich, aber wir haben ja einen unpaired Test, die Anzahl der Gene ist gleich, die Anzahl der cell lines ist unterschiedlich. 
Die Fehlermeldung tritt zu Beginn des for Loops für den Wilcoxon Test auf, für einzelne Werte funktioniert der Test.

Wir haben die Input Werte bereits auf NAs überprüft, es sind aber keine vorhanden. Deswegen wissen wir nicht, warum der Loop nicht durchläuft.

**Comment by XeniaTamara** [comment]
UPDATE: Uns ist gerade etwas sonderbares aufgefallen: in dem ```brain_cancer_exp``` dataframe gibt es an der Spalte 731 eine Spalte, bei der es nur 0 gibt, allerdings ist der Eintrag nicht wie bei anderen Spalten "0.0000" sondern nur "0". Wir vermuten, dass darum unser Loop gestockt hat und haben das Gen jetzt probeweise gelöscht und der for loop funktioniert!
Jetzt schauen wir beim Volcano plot weiter

**Comment by sholderbach** [comment]
Was sagt denn die Fehlermeldung?

**Comment by XeniaTamara** [comment]
Also es gibt ein Update :)
Uns ist etwas sonderbares bei Gen 731 aufgefallen. Bei diesem Gen steht statt dem klassischen "0.00000000" nur "0" weswegen wir vermuten, dass darum unser Loop nicht abgelaufen ist. Wir wollten die entries nun ersetzen, aber wenn wir einen Vektor erstellen wollen mit dem zuerst genannten 0-Wert ändert R das wieder in einfach nur 0 um.... Jetzt sind wir am überlegen das Gen einfach zu entfernen...Wäre das zulässig?

**Comment by sholderbach** [comment]
0 sollte es ja nach dem addieren von Pseudocounts nicht mehr geben. Z scaling sollte ja auch numeric zurueck geben und nicht integer. (0 scheint auf falschen wert-datentyp hinzuweisen)

**Comment by CedrikNeber** [comment]
<img width="780" alt="image" src="https://user-images.githubusercontent.com/82893911/124156965-89665000-da98-11eb-9a4b-e82a4efeedcb.png">

**Comment by sholderbach** [comment]
Ist das post transformation? Grundsaetzlich kann das jetzt einfach ein formatting quirk sein. und scheinbar mag wilcoxon es nicht wenn alles in einer gruppe  auf einen rank fallen wuerde??

**Comment by XeniaTamara** [comment]
Also wenn wir die Transformation machen ohne pseudocount kommt "NaN" statt dem Wert. Wenn man den pseudocount vor der Transformation addiert ist das Problem tatsächlich gelöst, da haben wir uns wohl in der Reihenfolge vertan. Wahrscheinlich hat unser Loop wegen dem "NaN" gespuckt. 
Danke für den Tipp!
Unser Volcano sieht trotzdem blöd aus :(  Wir werden dich dazu wahrscheinlich noch ein bisschen nerven, sorry für die vielen Nachrichten....

**Comment by XeniaTamara** [comment]
Also wenn wir die Transformation machen ohne pseudocount kommt "NaN" statt dem Wert. Wenn man den pseudocount vor der Transformation addiert, funktioniert die Addition tatsächlich. Doch der Loop funktioniert nicht, bzw. hat gerade einmal funktioniert, danach nicht mehr. 
Wir werden jetzt zwei Sachen versuchen: Einmal dieses Gen ganz zu löschen und dann, wie du auch schon gesagt hast, alle Gene löschen, bei der die Gene konstante Expressionen haben.

**Comment by ilya1010** [comment]
![image](https://user-images.githubusercontent.com/82601575/124169668-ca656100-daa6-11eb-8c4e-d05b10daf3b8.png)

**Comment by ilya1010** [comment]
Hallo Stefan,

unsere wilcoxon test mit z transformation hat endlich funktioniert und hier ist wie unseres volcano plot aussieht. Weisst du woran es liegen könnte?


Hier ist code dafür:

```
bc_exp_mean=apply(brain_cancer_exp[,b_correction],2, mean)
non_bc_exp_mean=apply(non_bc_exp[,b_correction],2,mean)

logfc<-log2(bc_exp_mean/non_bc_exp_mean)
logpv=log10(b_correction)
df <- data.frame(logfc,logpv)
library(ggplot2)
ggplot(df, aes(x=logfc, y=logpv)) +
  geom_point()
```

**Comment by ilya1010** [comment]
WIr haben gearade gesehen, dass unsere x achse sehr geschoben ist, es ist beim wert 55. Könntest du vieleich nochmal genau sagen wie wir die logs für volcano plot nehmen sollten?

Vielen Dank

**Comment by ilya1010** [comment]
![image](https://user-images.githubusercontent.com/82601575/124171731-3c3eaa00-daa9-11eb-9207-a24c72fa0d22.png)

Ein Update:)

**Comment by ilya1010** [comment]
![image](https://user-images.githubusercontent.com/82601575/124175232-a48f8a80-daad-11eb-9448-85fc91ed9f93.png)
 Wir haben absolute werte für log2folchange genommen, macht es sinn?
