### ISSUE TITLE
Universal drug and regression model

### ISSUE THREAD

**Issue by XeniaTamara** [datascience-mobi/2021-topic-01-team-03#8]
Hey Stefan, 
I just want to assure that my way to find an universal drug for the first regression model is right: 
Ilya told me that you suggested to chose a drug that works similar on all cell lines. So I calculated the variances for every effective drug on all cell lines and selected the drug with the lowest variance.

To check if I'm doing right, I plotted a histogram for every drug to check for uniform distribution. But when you look at the histograms, I don't know if the drug I' ve chosen is the best one. 

So, do you think it is the right way to select by variance or is there a way to select by uniform distribution?

**Comment by XeniaTamara** [comment]
![grafik](https://user-images.githubusercontent.com/82606553/124392462-05110880-dcf6-11eb-9f5c-686c2dd03c1c.png)
Here you can see the smal histograms for all 51 effective drug. The huge one is the one for the universal drug.

**Comment by sholderbach** [comment]
Pay attention that variance might scale with the magnitude/mean of the observed effect. So you might not want to bias against general low effectiveness. But a histogram approaching a Dirac delta would indicate uniform distribution! I would leave finding a good idea to solve this question up to you but you might want to think about what the area under the histogram could tell you...

**Comment by XeniaTamara** [comment]
Hey Stefan, 
sorry for bother you again but I have a problem with the KS test and I don't know how to solve it...
Since I am comparing my dataset, a discrete distribution, with the uniform distribution, a continuous distribution, there are ties present what generates the warning that no exact p-values can be computed. The test itself runs but leads to only two differing p-values over all 51 drugs, so a pretty annoying result.

I don't know whether I just have to accept this as output or whether something went wrong indicated by the warning. When something went wrong, I am wondering if I could use something like a "discrete uniform distribution", but I didn't find something like this on the internet, so maybe this is just stupid.

Could you give me some feedback why I get this output and if there is a way to modify the test?

![grafik](https://user-images.githubusercontent.com/82606553/124994053-8abdec80-e045-11eb-9fd9-36f456742358.png)

**Comment by XeniaTamara** [comment]
Hello again :)
I've got an update: I have found an advice on the internet to define a mean and a standard diviation in my test, so I did so. This lead to more different results but really low p-values, what is not that realistic.
Also, I think I have to consider how I want to deal with it when the minimum p-value occurs a few times. I think I need a second condition like chosing the drug with the lowest p-value and the lowest efficiency.
![grafik](https://user-images.githubusercontent.com/82606553/125066441-4bc68000-e0b3-11eb-8cd7-189c2966de24.png)

**Comment by XeniaTamara** [comment]
> But a histogram approaching a Dirac delta would indicate uniform distribution!

I am unsure if this is the right way as we want to have an consistent efficiency score.

**Comment by sholderbach** [comment]
Yes your not looking for actual uniform distribution with P(x1) = P(x2) but rather independent of the mean you want the values to be as close to the mean as possible.

**Comment by XeniaTamara** [comment]
But when I am not looking for uniform distribution which distribution do I need to take for my ks.test? 
I tried to model a dirac delta function with ```rnorm``` to fit the distributions from the histograms but it didn´t work out.

**Comment by XeniaTamara** [comment]
Since the test is not working we are wondering if we could choose the universal drug visually. So to argument that the drug we've chosen is the one with the highes frequency in one break. Is this valid?

**Comment by sholderbach** [comment]
Yes this sounds like a good solution. Bin all values with the same intervals and identify the drug for which the maximal count is observed in any bin.

**Comment by XeniaTamara** [comment]
Sounds good, I am going to try this tomorrow!
